### ISSUE TITLE
Doesn't seem to work in FF 37.0.1 Mac?

### ISSUE THREAD

**Issue by wandl** [sidorovich/clockwork-firebug#2]
Hi,

Have got the chrome extension working but cannot seem to get this one to work in Frebug is intsalled but have no clockwork tab?

Any ideas on how to fix this would rather use Firebug than chrome's developer tools..

Joseph

**Comment by sidorovich** [comment]
Hi, will check your bug. Which version of clockwork-firebug are you using?

**Comment by wandl** [comment]
I tried installing from: https://addons.mozilla.org/ru/firefox/addon/clockwork-for-firebug/  so  0.5.1
and also https://drive.google.com/file/d/0B0oH5QtMFjKKbk42QUNpVzBYQTA/view says 0.5 when installed

**Comment by sidorovich** [comment]
Cannot reproduce. Using FF 37.0.1 on MacOS X with Firebug 2.0.7 and Clockwork-Firebug 0.5.1 from Mozilla site.

Tab will be added on Net tab in Firebug. (my plugin have no independed tabs) Like on screenshot:
![](http://s23.postimg.org/6r05xb2or/2015_04_17_9_56_07.png)
 
Be sure, that you have correct Clockwork headers in HTTP response. 
You must have something like this:
```
X-Clockwork-Id: 1429253722.3622.1366834935
X-Clockwork-Version: 1.7
```
If you have no these headers in response - check your server-side settings, without these headers my plugin do not add own tab.

**Comment by wandl** [comment]
I can see that in the response headers:

X-Clockwork-Id	
1429254649.0382.754212014
X-Clockwork-Path	
/__clockwork/
X-Clockwork-Version	
1.7

**Comment by wandl** [comment]
Could be the server as I am using this: https://github.com/markguinn/silverstripe-clockwork works in chrome

**Comment by sidorovich** [comment]
Can you get content from clockwork with you browser by URL ```http://YOUR_DOMAIN/__clockwork/1429254649.0382.754212014``` ?

**Comment by sidorovich** [comment]
What about your problem? If you have solution - you can publish it here. If no - I try to help you.

**Comment by wandl** [comment]
Sorry for late response have been away, after re-installing and disabling enabling Firebug I can see the tab now! Thank you for your help!
